### PR TITLE
New error linking system, changes in error_box

### PR DESCRIPTION
**Pull request by valcikeric**
This PR adds a new system of linking errors, every linked error is now clickable and redirects the user to that errors' error_box and I've also changed the layout of the error_box a little as discussed in our last call.

On the page in the error boxes, I've used new icons for showing the relation between the current error code and the linked one. The icons are described in the title (showed when hovered over the icon) of the icon of linked errors. Also, each icon (=, >, <) has a title explaining its meaning again. I was a little hesitant if this was the right approach so I would be grateful for every feedback on it.

Also, when redirected to a linked error, that error is always collapsed. I believe there would be an easy JS solution to this, but I didn't want to go into that without asking first. Should I add a JS script that shows the error box that the user was redirected to?

### CODE REVIEW

**Review by mukrop — CHANGES_REQUESTED** [review]
Wow, good job, I'm impressed!
* A had minute design improvement suggestions, I commited them right away. (The </>/= icons are very nice!)
* Build check complains that Botan/CERT_NAME_NO_MATCH does not exist (the link leads nowhere), please have a look at that.
* What is the `_data/mapping-file.yml` for? If it's just a matter of presentation, you can capitalize using the [liquid filter](https://shopify.github.io/liquid/filters/capitalize/).
* When updating a branch to a new master, please do a rebase instead of a merge commit – the merge will aim for a rebase, thus raising a need to resolve all the conflicts again. Please rebase this branch onto current master.

The small adjustments above are enough for a merge. I'll seize the opportunity to mention what I see as important next (in the order of importance). It's of course up for discussion (and feel free to e.g. file issues for those, I'm just summarizing it here since it all comes to mind during the review.)
- Add Miska's new documentation for 6 done cases.
- Adjust the header. (Should I do it?)
- Add automatic testing for all example certificates for all libraries (that will probably need reworking the testing a bit). This will work as a cross-check for the mapping and your algorithm of propagating relationships (and will make us much more reliable as a source).
- Probably rename downloaded error cases to something more human-readable (OpenSSL error codes are no longer necessary and may be slightly confusing when the package is downloaded from a different library).

Smaller, nice to have (maybe do sooner if easy):
* Display multiple example certificates if we have them (as `ul` with zip, GitHub links and command in the same bullet?).
* When linking the the other error via URL anchor (`#`), the error should open the box.
* What about the books icons? I was thinking if it won't be better to get rid of them completely and just put the chain icon where at least one different book was. Ideas, comments?

**Comment by zacikpa** [comment]
> Add automatic testing for all example certificates for all libraries (that will probably need reworking the testing a bit). This will work as a cross-check for the mapping and your algorithm of propagating relationships (and will make us much more reliable as a source).

> Probably rename downloaded error cases to something more human-readable (OpenSSL error codes are no longer necessary and may be slightly confusing when the package is downloaded from a different library)


I would be up to take part in these two, maybe we could work it out with Eric over a call?

**Comment by mukrop** [comment]
As for me, splitting the work makes sense. My call availability over the next three days will be a bit unpredictable, but it moght fit.
Anyway, I think the points are pretty independent, so if Eric does agree, you can take them.

**Comment by valcikeric** [comment]
> Adjust the header. (Should I do it?)

I have no problem with doing it myself. Although, I think it would be better for you to exactly tell me what part of the text (or a brand new text segment) would be shown right off the bat, and what text would be shown after the user clicks on that "Show me more" button. And honestly, my JS skills aren't so great so my solution might be a little sloppy, but I'm up for the challenge.

> Display multiple example certificates if we have them (as `ul` with zip, GitHub links and command in the same bullet?).

I came across this when I was creating separate yaml files for each error from the other libraries. Some errors linked by more than one openssl error also had more than one `verify-cert`, but I deleted the excess ones and left just one pair of `verify-cert` and `verify-command`. I can add those deleted certs to all the error yaml files as e.g. `verify-cert-2`, `verify-cert-3`...

> When linking the the other error via URL anchor (`#`), the error should open the box.

I agree I will add this. I also mentioned it in the initial PR comment. On second thought, It might be nice to have it already in this PR, do you agree?

> What about the books icons? I was thinking if it won't be better to get rid of them completely and just put the chain icon where at least one different book was. Ideas, comments?

Yes, I like your idea. I think it would be overall better if a potential newcomer didn't have to learn that OpenSSL is red and Botan is green. I would ditch the books and coloring entirely.

I will work on the changes you mentioned. Pavel, I have no problem with you doing those two mentioned parts, they're yours.
I'm down for a call, I'm home and pretty much free every day until like 5 pm, so it's up to you guys.

**Comment by zacikpa** [comment]
> I came across this when I was creating separate yaml files for each error from the other libraries. Some errors linked by more than one openssl error also had more than one verify-cert but I deleted the excess ones 

We are talking about non-openssl errors here, right? 

> I can add those deleted certs to all the error yaml files as e.g. verify-cert-2, verify-cert-3

Yes,  please, add them back. Maybe try using the YAML array syntax when there is more of them:

`verify-certs:`
`  - example1`
`  - example2`
`...`

> and left just one pair of verify-cert and verify-command.

Another thing I realized: 
If we have more examples (verify-certs) linked to one error, we need a verify-command for each of them (they create pairs, as you say).

I'm thinking of moving the verify-command to each example instead. The command depends on how the example chain looks like, so having it there makes more sense to me. 
Do you think it's a good idea? Or do we rather want to have them as it is, maybe with a more friendly syntax, which makes the pairing obvious:

`verify:`
`  - example1: command1`
`  - example2: command2`

> I will work on the changes you mentioned. Pavel, I have no problem with you doing those two mentioned parts, they're yours.
I'm down for a call, I'm home and pretty much free every day until like 5 pm, so it's up to you guys.

Okay, thanks. I guess we can start working separately, and If some work overlaps and I need to consult, I'll get in touch with you.

**Comment by valcikeric** [comment]
> > I came across this when I was creating separate yaml files for each error from the other libraries. Some errors linked by more than one openssl error also had more than one verify-cert but I deleted the excess ones
> 
> We are talking about non-openssl errors here, right?

Yes.

Alright, I agree with all of the above. And regarding the `verify-certs`, I like your idea, I will come up with something.

**Comment by valcikeric** [comment]
I've done the changes required for a merge. I also addressed this issue:

> When linking the the other error via URL anchor (#), the error should open the box.

The PR should be mergeable now.

**Review by mukrop — APPROVED** [review]
Thanks for the adjusmtment.

Can you you prioritize the new docs? I would probably like to include a screenshot into the paper.

**Pull request merged**
