### PR TITLE
Add new (Miska's) documentation to 6 errors.

### PR DESCRIPTION
**Pull request by valcikeric**
I've added the documentation I found on our google drive.
I created a new icon (black, default colored library book icon) for our documentation, I think it fits well with the colored books we have right now, but it could be changed easily.

In the future, I think it would be nice to have the documentation saved as one big string in Markdown format and just parse it to HTML, but I had some issues implementing it like that, so I went this way. The output on the website would be the same.

This PR is ready to be merged.

### CODE REVIEW

**Review by mukrop — CHANGES_REQUESTED** [review]
Nice, thanks!
To be in line with what we write in the paper, I would like to have it from a single YAML field right away for better flexibility. The secret lies in `markdownify` filter and keeping the initial two spaces int eh multiline YAML string (see https://yaml-multiline.info/ for explanation of the YAML details). I recreated Expired cert in this form as an example.
Furthermore, we need to keep the intermediate titles (I styled h4 for them) and need to add links there (I'll probably do that later on with the review of the new documentation text).

What about right away incorporating the discussed adjustments of the iconography? For an existing documentation link, I would use the chain you introduced in cases where now there is at least one colored book (and as discussed, drop the colored books). For cases where we have new documentation, I would want something bold and catchy, what about [flag](https://fontawesome.com/icons/flag?style=solid) or [magic](https://fontawesome.com/icons/magic?style=solid)? And ideally in color (the primary color we use?) so that it catches attention (its one of the best features there, let's bring attention to it).

Do you think you can manage this in the first half if the week?
Thanks for the effort you put into this :+1:.

**Comment by valcikeric** [comment]
Yes, I can add that.  I will work on the things you mentioned and I think I can get it all done by Monday.

> For cases where we have new documentation, I would want something bold and catchy, what about flag or magic? And ideally in color (the primary color we use?)

As for the icon for the new documentation, I lean more towards the flag. And regarding the color, do you mean the red we now use for OpenSSL's errors?

**Comment by mukrop** [comment]
color: No, I meant blue (this blue is called "primary" in the basic
Bootstrap style)

>

**Comment by valcikeric** [comment]
I've done the requested changes, the web looks a little more black and white now, but I honestly don't think that's necessarily a problem. I also accordingly changed the intro, so please have a look at that.

The black book now represents original documentation from the library.

I've also done some minor bug fixes and changes:
- The python script now doesn't create a mapping file when the error doesn't have any corresponding errors.
- Now we show example certs for errors only if we have an example cert and corresponding verify command for that error. Some errors have an example cert, but no verify command for that cert in that library. In that case, we don't show the example cert now.

**Review by mukrop — APPROVED** [review]
Nice, I actually quite like the new look.
I was thinking of sugesting not to create the empty files with python, but decided it's not essential so we would sort that out llater. Glad you thought of that yourself as well!

**Pull request merged**
