### PR TITLE
Add pages with other libraries

### PR DESCRIPTION
**Pull request by valcikeric**
I've finally created GnuTLS', Botan's, and mbedTLS' own pages with errors. Right now the only things that I've changed are:

- I added three new pages with errors of the three mentioned libraries.
- In the navbar, I removed the errors dropdown and replaced it with links to the new library pages.
- And the title shown on the navbar when scrolled is no longer `Usable X.509 errors`, but changes to the name of the library.

I've done the sorting of the errors to categories by myself so please take a closer look at these changes, it is highly possible that some errors could have wrong category tags.
This PR is mergeable in my opinion.

### CODE REVIEW

**Comment by valcikeric** [comment]
As I was looking through the PR, I noticed some mistakes and errors. I feel ashamed that I hadn't checked these before submitting the PR. It should be fixed now.
Also, there are no linked errors with errors from Botan, GnuTLS, and mbedTLS right now, even when there should be, because some of them are linked by openssl errors. I originally planned to add the mapping in the next PR, but maybe it would be better to add it to this one.

**Review by mukrop — CHANGES_REQUESTED** [review]
Sorry for the slightly delayed review. Overall seems nice, several (mostly minor) comments below.
* Having the library in the navbar after scrolling is a nice touch, though I would also keep the website name. I. e. use _Usable X.509 errors: OpenSSL_ instead of just _OpenSSL_. (And thinking of that, I would probably merge `title` and `title-nav` on that since `title` gets used on page metadata and other places as wel...)
* The navbar element should be the same on all library pages for consistency of navigation. Use _Libraries_ instead of the specific library name please (but the highlighted libray after opening the combo box is definitely to be kept, that is great).
* I'm not sure what made you change the padding of sections, but you now break the visual of slightly shaded background (I know, id renders almost invisibly on your device :-/). ((I'll have to darken it a bit :-P.))
* Categorization of errors seems appropriate. The only place I was hesitant was the _Botan uncategorized_ section, where I think some errors could be put into other categories (but it's fuzzy, so I'd leave it as is for the moment).
* However, the errors often could have a better order within the sections. See OpenSSL – related errors (i.e. CRL-related, OCSP-related, ...) are always next to each other (which is often not the case for other libraries). Ideally, I would keep the sub-order as is in OpenSSL, if possible (e.g. for time-related errors always keep the order 1. cert-related, CRL-related, revoked).

**Comment by mukrop** [comment]
As fo the mapping, I'm OK for it to be the next PR after finalising this one.

**Comment by valcikeric** [comment]
I've done all the requested changes. It's ready for review.

> * I'm not sure what made you change the padding of sections, but you now break the visual of slightly shaded background (I know, id renders almost invisibly on your device :-/). ((I'll have to darken it a bit :-P.))

I haven't noticed any changes in the background, again 👎 . That's my mistake. I did those changes to move the vertical location of those links to libraries (e.g. `#openssl`) move a little higher. Without it, when the user was redirected to for example `x509errors.org/#openssl`, the `Time validity errors` headline was right under the navbar.
Now I found a solution that doesn't affect the visual background changes but does the same thing.

**Comment by valcikeric** [comment]
I also deleted `botan/CERT_NAME_NO_MATCH.yml`, because we already have an error called `CERT_NAME_NOMATCH`. Also the deleted error is not present in the Botan source `cert_status.cpp` we reference on our page.

**Review by mukrop — APPROVED** [review]
Nice, thanks.
Rebase the other branch on the new master and let's discuss the other changes :-).
(I'll wait for a PR.)

**Pull request merged**
