### PR TITLE
Preview revocation guides

### PR DESCRIPTION
**Pull request by mukrop**
Hi @Werxis. As mentioned, I'm moving to this pull request as it automatically generated a [preview page](https://x509errors-org--preview-revocation-guides-7lo8cooq.web.app). The preview page _should_ update with each push to the branch, though the deploy step is maybe broken (though works on `master`, we'll see).

EDIT: The preview auto-update seems to be working now.

### CODE REVIEW

**Comment by mukrop** [comment]
(Just to point it out, this changes the branch you should work on from `revocation guides` to `preview-revocation guides`!)

**Comment by mukrop** [comment]
I've checked all added content and I have to say I'm very satisfied with the result!

I've added multiple commits, roughly with the following (feel free to check yourself):
* Generated navigation links (both global in the header and local in the guides).
* Text proofreading (including wrapping in code samples).
* Consolidating the titles of all pages (not just the new guides).
* Generally updating the site (adding Majo as a contributor, updating About and FAQ pages,...).

From the position of the project maintainer, I'm happy to merge this PR now. I'm keeping it open for you, @Werxis, to check the changes and comment if you want. If there are no comments of yours, feel free to merge (deploy to production is automatic :-)).

**Comment by mukrop** [comment]
Oh, and since it's me who created this particular pull request, you need to approve it first before merging :-P.

**Review by Werxis — APPROVED** [review]
Looking good, approving and merging

**Pull request merged**
