### PR TITLE
Add static cert chains for errors we can't automatically replicate

### PR DESCRIPTION
**Pull request by zacikpa**

### CODE REVIEW

**Comment by mukrop** [comment]
@zacikpa, let me know here when will the PR be ready for review (as long as it's named "[WiP]", I expect it's not ready for review).

**Comment by zacikpa** [comment]
I don't plan on adding any new static certificates in the immediate future, so it can be merged now.
However, GitHub had some issues earlier today and as of now, it doesn't show the rest of the commits from the branch *static_certs*. I'm not sure what to do with that.

**Comment by mukrop** [comment]
Github had degraded services in the morning ([status report](https://www.githubstatus.com/)). Try to do push again, the git operation might have failed

**Comment by zacikpa** [comment]
Should be ready to merge now.

**Comment by mukrop** [comment]
Closing and reopening the PR to kick CI again.

**Pull request merged**
